# Generated by Django 3.2.7 on 2021-09-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
