# Generated by Django 3.2.7 on 2021-09-16 19:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_auto_20210915_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='prof'),
        ),
    ]
